# Generated by Django 5.1.1 on 2025-03-02 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('sup_id', models.UUIDField(default=uuid.UUID('fb931864-b811-44e7-ae43-8c1a2f455169'), editable=False, primary_key=True, serialize=False)),
                ('sup_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('doorno', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=50)),
                ('stat', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('purch_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('billno', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('bill', models.ImageField(upload_to='')),
                ('supp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.supplier')),
            ],
        ),
    ]
