# Generated by Django 5.1.1 on 2025-03-02 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill',
            field=models.ImageField(upload_to='img_src/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('49fa22ed-7ea3-4846-82da-17cdc94d0ea0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
