# Generated by Django 5.1.1 on 2025-03-02 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0003_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('4d455529-206d-4e82-a2f1-a81c68350038'), editable=False, primary_key=True, serialize=False),
        ),
    ]
