# Generated by Django 5.1.1 on 2025-03-02 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0004_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('261d7e24-194e-4347-85e1-6cb06de7bcac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
