# Generated by Django 5.1.1 on 2025-03-02 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0005_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('432af9b6-04a8-49bc-80b6-27ee54a6ab41'), editable=False, primary_key=True, serialize=False),
        ),
    ]
