# Generated by Django 5.1.1 on 2025-03-02 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0006_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('6b797260-0835-488e-ab19-886d11e40a97'), editable=False, primary_key=True, serialize=False),
        ),
    ]
