# Generated by Django 5.1.1 on 2025-03-02 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0007_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('dc0378f6-44e0-4170-a1f3-1e4938eb41da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
