# Generated by Django 5.1.1 on 2025-03-02 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0008_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('d10726a4-0891-43b5-a312-28c0222f1edc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
