# Generated by Django 5.1.1 on 2025-03-20 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0009_alter_purchase_bill_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('dc06e8b4-f6e8-4894-8712-030123a2cac9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('acceno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booktitle', models.CharField(max_length=100)),
                ('authorname', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('yearofpub', models.CharField(max_length=50)),
                ('rate', models.FloatField(max_length=40)),
                ('classfic', models.CharField(max_length=50)),
                ('ava', models.CharField(max_length=50)),
                ('purc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.purchase')),
                ('suppl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.supplier')),
            ],
        ),
    ]
