# Generated by Django 5.1.1 on 2025-03-20 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0010_alter_supplier_sup_id_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('memname', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('doorno', models.CharField(max_length=50)),
                ('strnme', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('memtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('ac2a5940-217f-48a3-977f-331c656f493e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
