# Generated by Django 5.1.1 on 2025-03-20 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0011_member_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('48370b44-98a2-4a83-8ca4-e48657862e84'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_date', models.DateField()),
                ('ret_date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.stock')),
                ('mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.member')),
            ],
        ),
    ]
