# Generated by Django 5.1.1 on 2025-04-01 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0012_alter_supplier_sup_id_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('987fcceb-c04e-4ae2-8c52-3093de2b1edb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
