# Generated by Django 5.1.1 on 2025-04-02 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0014_issue_cno3_supplier_cno_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.UUIDField(default=uuid.UUID('036a198d-e86d-4f6c-9e9d-821d6ae9847f'), editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cno3',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cno',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('6c97265f-65a3-42c2-adfc-1a92c0f99214'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='cno4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='cno2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='cno3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='cno1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
    ]
