# Generated by Django 5.1.1 on 2025-04-02 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0015_common_remove_issue_cno3_remove_supplier_cno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='cno4',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cno3',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cno1',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cno2',
        ),
        migrations.AddField(
            model_name='supplier',
            name='cno',
            field=models.UUIDField(default=uuid.UUID('a6d2ea33-7964-4677-a8f3-80a8518bda6a'), editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('2975d571-799b-4305-89f5-ac0c1cb8f095'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='common',
        ),
    ]
