# Generated by Django 5.1.1 on 2025-04-02 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0016_remove_issue_cno4_remove_stock_cno3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.UUIDField(default=uuid.UUID('2fd102d2-0fbe-11f0-876c-f8b46a204f0d'))),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cno',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('69683c46-2ed8-447c-89bf-37d442a506c2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='cno4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='cno2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='cno3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='cno1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
    ]
