# Generated by Django 5.1.1 on 2025-04-02 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0017_common_remove_supplier_cno_alter_supplier_sup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='cno',
            field=models.UUIDField(default=uuid.UUID('7f5d2d00-0fbe-11f0-84db-f8b46a204f0d')),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('18902b32-9444-40f9-bcb5-a6899335866b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
