# Generated by Django 5.1.1 on 2025-04-02 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0018_alter_common_cno_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='cno',
            field=models.UUIDField(default=uuid.UUID('2b801c72-5fba-4a3c-946e-a28750d63759')),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('f60c0450-aee5-4fda-8ff7-108832ec8d2d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
