# Generated by Django 5.1.1 on 2025-04-02 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0019_alter_common_cno_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cno2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cno1',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cno3',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cno4',
        ),
        migrations.AddField(
            model_name='supplier',
            name='cno',
            field=models.UUIDField(default=uuid.UUID('87c02f88-1468-41ba-8f41-fa565b7770e7'), editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('f81728ea-60b2-4dce-8216-f56d27cfb8bf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='common',
        ),
    ]
