# Generated by Django 5.1.1 on 2025-04-02 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0020_remove_purchase_cno2_remove_supplier_cno1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='common',
            fields=[
                ('cno', models.UUIDField(default=uuid.UUID('e11825f4-72af-4b14-8892-b1d2cda69b65'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cno',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('79b92d14-f7f7-4632-9bca-0d71818bfbd3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='cno3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='cno2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='cno3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='cno1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreapp.common'),
            preserve_default=False,
        ),
    ]
