# Generated by Django 5.1.1 on 2025-04-02 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0021_common_remove_supplier_cno_alter_supplier_sup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cno3',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cno3',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cno2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cno1',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_id',
            field=models.UUIDField(default=uuid.UUID('e0d191f0-f41a-4045-9c72-dd1c45782ee1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='common',
        ),
    ]
