# Generated by Django 5.1.1 on 2025-04-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0023_alter_supplier_sup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='isbn',
            field=models.CharField(default=4, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='qun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='rack',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
