# Generated by Django 5.1.1 on 2025-04-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0025_tot_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
