# Generated by Django 5.1.1 on 2025-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0026_issue_actual_date_issue_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ava_issue',
            field=models.CharField(default=7, max_length=10),
            preserve_default=False,
        ),
    ]
