# Generated by Django 5.1.1 on 2025-04-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0028_rename_ava_issue_issue_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issued',
            field=models.CharField(default='No', editable=False, max_length=10),
        ),
    ]
