# Generated by Django 5.1.1 on 2025-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0030_issue_paymth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='paymth',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
