# Generated by Django 5.1.1 on 2025-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0032_alter_issue_paymth'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supp_id',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='tot_worth',
        ),
    ]
