# Generated by Django 5.1.1 on 2025-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0033_supplier_supp_id_delete_tot_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supp_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
