# Generated by Django 5.1.1 on 2025-05-05 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0034_alter_supplier_supp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='id',
        ),
        migrations.AddField(
            model_name='issue',
            name='issu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
