# Generated by Django 5.1.1 on 2025-05-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0035_remove_issue_id_issue_issu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invcno', models.IntegerField(editable=False, max_length=10, unique=True)),
                ('dat', models.DateField()),
                ('prod', models.CharField(max_length=30)),
                ('amount', models.IntegerField(max_length=10)),
                ('mem_dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.member')),
                ('sto_dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.stock')),
            ],
        ),
    ]
