# Generated by Django 5.1.1 on 2025-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0036_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
