# Generated by Django 5.1.1 on 2025-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0037_alter_sales_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='prod',
        ),
        migrations.AddField(
            model_name='sales',
            name='perunt',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='qunt',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
