# Generated by Django 5.1.1 on 2025-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0038_remove_sales_prod_sales_perunt_sales_qunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tot',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
