# Generated by Django 5.1.1 on 2025-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0039_sales_tot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='invcno',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
