# Generated by Django 5.1.1 on 2025-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0040_alter_sales_invcno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='mem_dt',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sto_dt',
            field=models.CharField(max_length=30),
        ),
    ]
