# Generated by Django 5.1.1 on 2025-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0041_alter_sales_mem_dt_alter_sales_sto_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sto_dt',
            new_name='bkisbn_dt',
        ),
        migrations.AddField(
            model_name='sales',
            name='bktit_dt',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
