# Generated by Django 5.1.1 on 2025-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0042_rename_sto_dt_sales_bkisbn_dt_sales_bktit_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='perunt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
