# Generated by Django 5.1.1 on 2025-05-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0043_alter_sales_amount_alter_sales_perunt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='bkisbn_dt',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='bktit_dt',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='perunt',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='qunt',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tot',
        ),
        migrations.CreateModel(
            name='saledt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkisbn_dt', models.CharField(max_length=30)),
                ('bktit_dt', models.CharField(max_length=20)),
                ('perunt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qunt', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreapp.sales')),
            ],
        ),
    ]
