# Generated by Django 5.1.1 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreapp', '0044_remove_sales_amount_remove_sales_bkisbn_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledt',
            name='tot',
        ),
        migrations.AddField(
            model_name='sales',
            name='tot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
